### ISSUE TITLE
transform vs transformed

### ISSUE THREAD

**Issue by worbit** [dbt-ethz/mola#50]
in **compas**, most methods come in two versions, `transform` and `transformed` (or scale and scaled, move and moved, etc.) where one acts on the instance itself, and the other returns a transformed copy but remains the original untouched. is there a possible scenario where we would need these two options as well?

**Comment by modellstadt** [comment]
I thought we organized this already?
The add version should manipulate itself and return itself. This allows chaining. The other version we would be the utils method which takes two as input and returns a new one. 

If think otherwise it gets a bit confusing.
If one wants a copy, one could also write
my_instance.copy().add()
I think this would be intuitive, and the code would be readable without any explanation?
